In [93]:
import pandas as pd
import numpy as np

In [94]:
data = pd.read_csv("C:/Users/User/Documents/Jupyter Exercises/Car Data Analysis/tutorials.csv")

In [95]:
data

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499
81,3,?,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
title = ["symbol","normali-loss","make","fuel","aspirnt","doors","body","wheels","eng-location",
         "wheel-base","length","width","height","curb-weight","engine-type","no-cylinders","engine-size",
         "fuel-system","bore","stroke","compresn-ratio","horse-power","rpm","city-l/km","high_way - l/km","price"]

In [97]:
data.columns = title

In [98]:
data

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499
81,3,?,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
data.describe()

,symbol,wheel-base,width,height,curb-weight,engine-size,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km
count,82.000000,82.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000
mean,0.914634,98.687805,66.020988,53.171605,2536.913580,130.234568,9.789012,104.469136,5229.629630,25.172840,30.555556
std,1.102200,6.774597,2.682290,2.439582,640.843315,56.309251,3.488467,40.178068,509.397793,7.703555,8.110179
min,-1.000000,86.600000,60.300000,47.800000,1488.000000,61.000000,7.000000,48.000000,4200.000000,13.000000,16.000000
25%,0.000000,93.700000,64.000000,50.800000,1989.000000,92.000000,8.500000,70.000000,4800.000000,19.000000,25.000000
50%,1.000000,96.500000,65.200000,53.500000,2385.000000,110.000000,9.000000,100.000000,5400.000000,24.000000,30.000000
75%,1.750000,101.800000,66.500000,54.500000,2824.000000,140.000000,9.400000,121.000000,5500.000000,31.000000,38.000000
max,3.000000,120.900000,72.000000,59.800000,4066.000000,326.000000,22.700000,262.000000,6000.000000,49.000000,54.000000

In [100]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   symbol           82 non-null     int64
 1   normali-loss     82 non-null     object
 2   make             82 non-null     object
 3   fuel             82 non-null     object
 4   aspirnt          82 non-null     object
 5   doors            82 non-null     object
 6   body             82 non-null     object
 7   wheels           82 non-null     object
 8   eng-location     82 non-null     object
 9   wheel-base       82 non-null     float64
 10  length           82 non-null     object
 11  width            81 non-null     float64
 12  height           81 non-null     float64
 13  curb-weight      81 non-null     float64
 14  engine-type      81 non-null     object
 15  no-cylinders     81 non-null     object
 16  engine-size      81 non-null     float64
 17  fuel-system      81 non-null     object
 18  bore             81 non-null     object
 19  stroke           81 non-null     object
 20  compresn-ratio   81 non-null     float64
 21  horse-power      81 non-null     float64
 22  rpm              81 non-null     float64
 23  city-l/km        81 non-null     float64
 24  high_way - l/km  81 non-null     float64
 25  price            81 non-null     object
dtypes: float64(10), int64(1), object(15)
memory usage: 16.8+ KB

In [101]:
data.replace("?",np.NaN,inplace = True)

In [102]:
data

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499
81,3,NaN,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
data.isnull().sum()

symbol              0
normali-loss       22
make                0
fuel                0
aspirnt             0
doors               2
body                0
wheels              0
eng-location        0
wheel-base          0
length              0
width               1
height              1
curb-weight         1
engine-type         1
no-cylinders        1
engine-size         1
fuel-system         1
bore                5
stroke              5
compresn-ratio      1
horse-power         1
rpm                 1
city-l/km           1
high_way - l/km     1
price               4
dtype: int64

In [104]:
mean_norm = data["normali-loss"].astype("float").mean(axis = 0)

In [105]:
mean_norm

128.53333333333333

In [106]:
data["normali-loss"].replace(np.NaN,mean_norm,inplace = True)

In [107]:
data

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,128.533333,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500
1,1,128.533333,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450
4,2,128.533333,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499
81,3,128.533333,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
data.isnull().sum()

symbol             0
normali-loss       0
make               0
fuel               0
aspirnt            0
doors              2
body               0
wheels             0
eng-location       0
wheel-base         0
length             0
width              1
height             1
curb-weight        1
engine-type        1
no-cylinders       1
engine-size        1
fuel-system        1
bore               5
stroke             5
compresn-ratio     1
horse-power        1
rpm                1
city-l/km          1
high_way - l/km    1
price              4
dtype: int64

In [109]:
data["doors"].value_counts()

doors
two     44
four    36
Name: count, dtype: int64

In [110]:
data["doors"].replace(np.NaN,"two",inplace = True)

In [111]:
data

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,128.533333,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500
1,1,128.533333,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450
4,2,128.533333,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499
81,3,128.533333,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
data.isnull().sum()

symbol             0
normali-loss       0
make               0
fuel               0
aspirnt            0
doors              0
body               0
wheels             0
eng-location       0
wheel-base         0
length             0
width              1
height             1
curb-weight        1
engine-type        1
no-cylinders       1
engine-size        1
fuel-system        1
bore               5
stroke             5
compresn-ratio     1
horse-power        1
rpm                1
city-l/km          1
high_way - l/km    1
price              4
dtype: int64

In [113]:
data["width"]

0     64.1
1     65.5
2     66.2
3     66.4
4     66.3
      ...
77    64.4
78    63.8
79    65.4
80    65.4
81     NaN
Name: width, Length: 82, dtype: float64

In [114]:
mean_width = data["width"].astype("float").mean(axis = 0)
mean_width

66.02098765432098

In [115]:
data["width"].replace(np.NaN,mean_width,inplace = True)

In [116]:
mean_height = data["height"].astype("float").mean(axis = 0)
data["height"].replace(np.NaN,mean_height,inplace = True)

mean_curb_weight = data["curb-weight"].astype("float").mean(axis = 0)
data["curb-weight"].replace(np.NaN,mean_curb_weight,inplace = True)

In [117]:
data["engine-type"]

0     dohc
1     ohcv
2      ohc
3      ohc
4      ohc
      ...
77     ohc
78     ohc
79     ohc
80     ohc
81     NaN
Name: engine-type, Length: 82, dtype: object

In [118]:
data["engine-type"].value_counts()

engine-type
ohc      67
ohcv      7
rotor     4
dohc      3
Name: count, dtype: int64

In [119]:
data["engine-type"].replace(np.NaN,"ohc",inplace = True)

In [120]:
data["fuel-system"]

0     mpfi
1     mpfi
2     mpfi
3     mpfi
4     mpfi
      ...
77    2bbl
78    spdi
79    spdi
80    2bbl
81     NaN
Name: fuel-system, Length: 82, dtype: object

In [121]:
data["fuel-system"].value_counts()

fuel-system
mpfi    30
2bbl    27
1bbl    11
idi      6
4bbl     3
spdi     2
mfi      1
spfi     1
Name: count, dtype: int64

In [122]:
data["fuel-system"].replace(np.NaN,"mpfi",inplace = True)

In [123]:
mean_bore = data["bore"].astype("float").mean(axis = 0)
data["bore"].replace(np.NaN,mean_bore,inplace = True)

In [124]:
mean_compresn_ratio = data["compresn-ratio"].astype("float").mean(axis = 0)
data["compresn-ratio"].replace(np.NaN,mean_compresn_ratio,inplace = True)

In [125]:
mean_horse_power = data["horse-power"].astype("float").mean(axis = 0)
data["horse-power"].replace(np.NaN,mean_horse_power,inplace = True)

In [126]:
mean_rpm = data["rpm"].astype("float").mean(axis = 0)
data["rpm"].replace(np.NaN,mean_rpm,inplace = True)

In [127]:
mean_city_l_km = data["city-l/km"].astype("float").mean(axis = 0)
data["city-l/km"].replace(np.NaN,mean_city_l_km,inplace = True)

In [128]:
mean_high_way_l_km = data["high_way - l/km"].astype("float").mean(axis = 0)
data["high_way - l/km"].replace(np.NaN,mean_high_way_l_km,inplace = True)

In [129]:
mean_stroke = data["stroke"].astype("float").mean(axis = 0)
data["stroke"].replace(np.NaN,mean_stroke,inplace = True)

In [130]:
data.isnull().sum()

symbol             0
normali-loss       0
make               0
fuel               0
aspirnt            0
doors              0
body               0
wheels             0
eng-location       0
wheel-base         0
length             0
width              0
height             0
curb-weight        0
engine-type        0
no-cylinders       1
engine-size        1
fuel-system        0
bore               0
stroke             0
compresn-ratio     0
horse-power        0
rpm                0
city-l/km          0
high_way - l/km    0
price              4
dtype: int64

In [131]:
data.dropna(subset = "price", axis = 0, inplace = True)

In [132]:
data

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,128.533333,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500
1,1,128.533333,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450
4,2,128.533333,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6189
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499

In [133]:
82-78

4

In [134]:
data.dtypes

symbol               int64
normali-loss        object
make                object
fuel                object
aspirnt             object
doors               object
body                object
wheels              object
eng-location        object
wheel-base         float64
length              object
width              float64
height             float64
curb-weight        float64
engine-type         object
no-cylinders        object
engine-size        float64
fuel-system         object
bore                object
stroke              object
compresn-ratio     float64
horse-power        float64
rpm                float64
city-l/km          float64
high_way - l/km    float64
price               object
dtype: object

In [135]:
data["bore"] = data["bore"].astype("float")
data["price"] = data["price"].astype("float")

In [136]:
data.dtypes

symbol               int64
normali-loss        object
make                object
fuel                object
aspirnt             object
doors               object
body                object
wheels              object
eng-location        object
wheel-base         float64
length              object
width              float64
height             float64
curb-weight        float64
engine-type         object
no-cylinders        object
engine-size        float64
fuel-system         object
bore               float64
stroke              object
compresn-ratio     float64
horse-power        float64
rpm                float64
city-l/km          float64
high_way - l/km    float64
price              float64
dtype: object

In [137]:
data

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,128.533333,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
1,1,128.533333,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.4,10.0,102.0,5500.0,24.0,30.0,13950.0
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.4,8.0,115.0,5500.0,18.0,22.0,17450.0
4,2,128.533333,audi,gas,std,two,sedan,fwd,front,99.8,...,136.0,mpfi,3.19,3.4,8.5,110.0,5500.0,19.0,25.0,15250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6189.0
77,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92.0,2bbl,2.97,3.23,9.4,68.0,5500.0,31.0,38.0,6669.0
78,1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,...,98.0,spdi,3.03,3.39,7.6,102.0,5500.0,24.0,30.0,7689.0
79,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110.0,spdi,3.17,3.46,7.5,116.0,5500.0,23.0,30.0,9959.0
80,3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,...,122.0,2bbl,3.35,3.46,8.5,88.0,5000.0,25.0,32.0,8499.0

In [139]:
data.to_csv("C:/Users/User/Documents/Jupyter Exercises/Car Data Analysis/tutorials clean.csv")